name: Build Draftz

on:
  workflow_dispatch:

jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libfltk1.3-dev

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: Draftz-Linux
          path: build/Draftz

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install FLTK
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install fltk:x64-windows

      - name: Configure
        run: |
          cmake -B build `
          -A x64 `
          -DCMAKE_TOOLCHAIN_FILE="$pwd\vcpkg\scripts\buildsystems\vcpkg.cmake"

      - name: Build
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: Draftz-Windows
          path: build/Release/Draftz.exe

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install FLTK
        run: |
          brew install fltk cmake

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: Draftz-macOS
          path: build/Draftz
